### ISSUE TITLE
Dashboard-Saliencies

### ISSUE THREAD

**Issue by ConstantinosM** [jostosh/deeprl#2]
I was wondering what did you use to make the dashboard in your videos. Also are the saliencies calculated based on gradient-based methods?

**Comment by jostosh** [comment]
Hi there, thanks for your interest! Yes, the saliences are just the absolute gradients of the max policy output w.r.t. to the input placeholder (the current frame) or the critic's output w.r.t. to the current frame.

As for the 'dashboard', in fact, you're just looking at a subplot grid that I created with `matplotlib`. The video takes quite some time to generate because `matplotlib`'s rendering is pretty slow (or at least I haven't dug into it to make it fast). So basically, every single frame in the video is a subplot that I created with `matplotlib` which I then convert to a `numpy` array using [this trick](https://stackoverflow.com/questions/35355930/matplotlib-figure-to-image-as-a-numpy-array). I then combine these `numpy` arrays to make a video using a `VideoWriter` from the `skvideo` package.

**Comment by jostosh** [comment]
The code is actually hidden in this repo [somewhere](https://github.com/jostosh/deeprl/blob/a0f958e9428ecd6ed7ca115793989b7e3d69673f/experiments/demo/visualize.py). It is a real mess I have to admit since my debugging method was just visual trial and error and I only had to use the script a few times in the end. Anyway, good luck on getting yours right!

**Comment by ConstantinosM** [comment]
Great work and thanks a lot for the prompt and detailed response!
